# Generated by Django 3.0.5 on 2020-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(default='cbd32fe6', max_length=8)),
                ('name', models.CharField(default='', max_length=20)),
                ('language', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
