# Generated by Django 3.0.5 on 2020-08-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='idd',
        ),
    ]
