# Generated by Django 3.0.5 on 2020-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0002_remove_details_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='id',
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
